<?php
require('config/config.php');
include_once('functions/authentication.php');
require_once('functions/db_functions.php');
require_once('functions/forms_teacher.php');
require_once('functions/forms_director.php');
require_once('functions/internals.php');
require_once('functions/cutlist.php');
require_once('functions/attendance.php');
require_once('functions/common.php');
require_once('modules/parsecsv/parsecsv.lib.php');
require_once('dompdf_config.inc.php');
require_once('functions/form_structure.php');
require_once('functions/teacher.php');
require_once('functions/nba_incharge.php');
require_once('functions/course_admins.php');
require("Mail.php");
?>
